# Generated by Django 6.0 on 2025-12-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booking_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
