# Generated by Django 6.0 on 2026-01-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_booking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('music', 'Music / DJ'), ('performance', 'Play / Performance')], default='music', max_length=20),
        ),
    ]
